blank_issues_enabled: true
contact_links:
  - name: Morse Trainer Discussions
    url: https://github.com/EmmanuelPleshe/mymorsetrainer/discussions
    about: Ask questions, share tips, or show off your progress!
